# Generated by Django 4.0.5 on 2022-07-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('done', 'Done'), ('error', 'Error'), ('created', 'Repo created, waiting for requirement gathering')], default='created', max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RepoRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('repos', models.ManyToManyField(related_name='repo_requirements', to='home.repoitem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reporequirement',
            constraint=models.UniqueConstraint(fields=('version', 'name'), name='unique_requirement'),
        ),
    ]
